### ISSUE TITLE
Signing with PKCS#11 keypair that has no X.509 certificate

### ISSUE THREAD

**Issue by zosocanuck** [sigstore/cosign#1037]
Hi,

I'm using the latest P11 functionality in 1.3.0 and noticed this issue.  Note that I do not run into this issue if the P11 keypair has an associated X.509 certificate

```
cosign sign --key "pkcs11:token=Remote%20Token;slot-id=0;id=%43%6f%73%69%67%6e%2d%6b%65%79%70%61%69%72%2d%63%6f%73%69%67%6e%2d%65%63%64%73%61;object=mykeypair?module-path=/usr/local/lib/myhsm.so&pin-value=1234" xxx/yyy:0.1 -d

Error: signing [xxx/yyy:0.1]: getting signer: nil certificate provided
main.go:48: error during command execution: signing [xxx/yyy:0.1]: getting signer: nil certificate provided
```

**Comment by garantir-km** [comment]
Hi @zosocanuck. I think this is due to this check 
https://github.com/garantir-km/cosign/blob/84c94b6361848bfac9e083483b66f41e55c3d613/cmd/cosign/cli/sign/sign.go#L345
We should check for `certFromPKCS11` being `nil` instead. Can you please try with [this](https://github.com/garantir-km/cosign/tree/fix-pkcs11-no-cert) branch ?

**Comment by zosocanuck** [comment]
@garantir-km This resolved the issue. Thanks.
