### ISSUE TITLE
Custom naming pem and key files

### ISSUE THREAD

**Issue by Knibbaz** [sigstore/cosign#1076]
**Question**
I was wandering if it would be possible to change the name of the pem and key files while creating them. Something like cosign generate-key-pair --name project-3

**Comment by ChrisJBurns** [comment]
I can pick this up as a starter issue, am already familiar with `cobra` and `viper`?

**Comment by znewman01** [comment]
Yeah this should be relatively straightforward! Thank you very much, let me know if you get stuck at any point. See also https://github.com/sigstore/cosign/pull/1077 which implements this (it won't apply cleanly since a lot has changed).

Might be nice to touch up `cosign import-key-pair` while you're at it too 😄

**Comment by ChrisJBurns** [comment]
@znewman01  What kind of touchup to `import-key-pair` do you have in mind? Are you suggesting adding the `--name` flag to that command also so that it isn't hardcoded to `import-cosign.key` & `import-cosign.pub` ?

I've also realised, there is a [`todo`](https://github.com/sigstore/cosign/blob/main/pkg/cosign/keys.go#L77) to move the `ImportKeyPair` function back into `cmd/cosign/cli/importkeypair` however, it is used in the [`e2e`](https://github.com/sigstore/cosign/blob/main/test/e2e_test.go#L1160) tests - unless you're suggesting to move it and just change the reference in the `e2e` tests?

**Comment by znewman01** [comment]
> Are you suggesting adding the --name flag to that command also so that it isn't hardcoded to import-cosign.key & import-cosign.pub ?

Exactly 😄 

> unless you're suggesting to move it and just change the reference in the e2e tests?

Happy for you to *either* do that *or* leave it as-is.

> Have added the --name functionality to the generate-key-pair let me know your thought's https://github.com/sigstore/cosign/pull/2561

TYVM! Will TAL soon

**Comment by ChrisJBurns** [comment]
I shall submit the `import-key-pair` change under a different PR but will attach to this issue also.
