### ISSUE TITLE
`cosign download sbom` for multi-arch images

### ISSUE THREAD

**Issue by mattmoor** [sigstore/cosign#1086]
**Description**

This came up developing: https://github.com/google/ko/pull/506

Basically what we're doing in `ko` with multi-arch builds is producing an SBOM attached to each image.  However, `cosign download sbom` only does a shallow look, and reports that there are no SBOMs.

I think that we should first check the index, but if nothing is found (or maybe regardless) walk the child images looking for additional SBOMs.  This should be trivial to do by wrapping what we have in `walk.SignedEntity` to collect things recursively.

**Comment by mattmoor** [comment]
We could also take a `--platform` option to resolve a particular platform's SBOM, if we choose to default `linux/amd64`, as some clients do.

**Comment by mattmoor** [comment]
cc @imjasonh FYI

**Comment by ribbybibby** [comment]
I bumped into this recently. For now I'm doing the following to resolve the platform-specific image, but it might be nice if `cosign` could do this itself.
```
cosign download sbom ghcr.io/google/ko@$(crane digest ghcr.io/google/ko:latest --platform=linux/amd64)
```

It occurs to me that this isn't just an issue for `download sbom`. It could equally apply to signatures, attestations and basically any command where you're actually interested in the platform-specific image rather than the index. Or where you're interested in all the children of an index.

Perhaps it requires a more general solution for handling multi-arch images? I know `sign`, for instance, already has a `--recursive` option.

Or, alternatively, leave it up to the caller of cosign to figure out which images they want to target? Like I'm doing above with `crane`.

**Comment by mattmoor** [comment]
cc @puerco given recent conversations about multi-arch.

**Comment by imjasonh** [comment]
> ```
> cosign download sbom ghcr.io/google/ko@$(crane digest ghcr.io/google/ko:latest --platform=linux/amd64)
> ```

This seems like it means we should just support `cosign download sbom [IMG] --platform`, where if platform is unset, fetch the SBOM for the image or index, and if it is set, iff it's an index, fetch the SBOM attached to that platform's image.

(Same for all the attachment types, not just SBOMs)

**Comment by ribbybibby** [comment]
@imjasonh That would be great. I think it could also extend more widely to commands like `triangulate`.

**Comment by amouat** [comment]
This bit me recently. Whilst we're working on a solution, would it be worth rewording the error message? At the moment I get: 

```
Error: image not found in registry
main.go:52: error during command execution: image not found in registry
```

We could say something like "Failed to locate SBOM. This may be because there a multiple variants of the image for different environments. Try running `crane digest ghcr.io/google/ko:latest --platform=linux/amd64` for your platform to identify the digest of the image you're using."

I accept that is still confusing, so maybe it's easiest to come up with a proper solution :)
