### ISSUE TITLE
Can URL output by sign-blob be public?

### ISSUE THREAD

**Issue by pdxjohnny** [sigstore/cosign#1416]
If one were to run the following setup via pubic CI, would that pose a security risk? Would it be bad if anyone could see the OAuth URL?

https://github.com/sigstore/cosign/blob/main/FUN.md#level-11

**Comment by dlorenc** [comment]
cc @bobcallaway

**Comment by bobcallaway** [comment]
In general, I don't think it poses a security risk (but would opt to hide it by default):

(a) it is unlikely that this would even work because it would require you to fully automate the browser (and subsequent HTTP traffic) within the CI process to complete the OAuth2 dance to get the ID token

(b) only other processes on the same CI runner would have access to post to the loopback address where the `redirect_uri` is pointed, so even if someone did read the value of `state` they wouldn't be able to replay it without having access to the runner

(c) in addition, the `code_challenge` value is held in memory of the `cosign` process and if you can reverse a SHA256 hash to a value then we have bigger problems in the industry :/

So net: I think its a good question but I personally don't believe it poses a risk.
