### ISSUE TITLE
Don't panic: If a remote TUF root if corrupt, fallback on the embedded

### ISSUE THREAD

**Issue by asraa** [sigstore/cosign#1506]
**Description**

We hit this bug over the last few days: the GCS TUF root ended up in an expired and then corrupt state, which caused cosign to segfault. We should fallback on embedded targets when a TUF root fails verification (and log a warning to report maybe)

**Comment by asraa** [comment]
cc @dlorenc @haydentherapper @priyawadhwa 
I am so sorry :/

**Comment by haydentherapper** [comment]
I’m not sure we should fall back to embedded targets. This opens us up to various attacks. Say the keys associated with the embedded targets get compromised and we rotate the targets- now an attacker can target someone with a MitM attack to trick the client into trusting the local targets. 

We should gracefully handle this error though.

**Comment by haydentherapper** [comment]
It’s a trade off between usability and security. Since TUF forms the root of trust for this ecosystem, I’d prefer to lean towards security for these types of issues. 

When I said gracefully I just meant to return an error and exit.

**Comment by dlorenc** [comment]
What's the risk of falling back? It's either valid or it's not right? And the embedded one expires, so I don't think I'm clear on the additional risk.

**Comment by haydentherapper** [comment]
I'm thinking where if for some reason the embedded targets have been compromised, and an attacker tricks a client into seeing the TUF root is corrupted through MitM.

**Comment by znewman01** [comment]
What @haydentherapper is advocating is definitely the "right" thing to do. IMO the question is: what are the odds that a target gets compromised and revoked, *and* the attacker has the ability to cause some clients to be unable to connect (e.g., via a DoS attack) -- it's easier than a fully general MITM. To me that feels like a scenario we want to cover so my vote is exit (with a clear explanation of what's going on) rather than fall back.

The tradeoff of course is that cosign stops working in the event of a real outage, or doesn't work in non-internet environments. We could have an "offline" mode with big warnings that it's less secure? And the nice thing too is that the TUF metadata is public so we can have mirrors for it that we fall back to.

**Comment by dlorenc** [comment]
I think the part I'm stuck on is that the embedded root is literally embedded. It can't be tampered with without modifying cosign itself, so it's defacto trusted. If you can compromise the client then nothing else matters. It's either still valid, unexpired, and trusted, or expired.

**Comment by dlorenc** [comment]
But I guess in this case we wouldn't even attempt to fetch the remote one, so maybe it's moot?

**Comment by haydentherapper** [comment]
I'm thinking about where the keys that sign off on the embedded root become compromised or if the private keys associated with the targets are compromised. Under normal operations this is fine, we'd just issue a new TUF root or sign new targets, update the remote, and Cosign would pick up the update. I want to treat the embedded root as only a root of trust.

**Comment by dlorenc** [comment]
Ahhh sorry - I think I was using root and metadata interchangeably. This makes sense now I think.

**Comment by dlorenc** [comment]
I think we decided against this one?

**Comment by dlorenc** [comment]
Reopen if I'm missing something!
