### ISSUE TITLE
ClusterImagePolicy CRD Status implementation

### ISSUE THREAD

**Issue by vaikas** [sigstore/cosign#1574]
What should we have in the Status field for the CRD. Seems like an obvious one might be that the information has been properly jotted down into a ConfigMap used by Cosign webhook?

**Comment by hectorj2f** [comment]
@vaikas I have not seen any examples of Policy types (CRDs) on Kubernetes ecosystem with a status field.I am not sure if it's something we need to explore, at least yet. For instance, the NetworkPolicy and/or the PodSecurityPolicy didn't have this status field, in addition, it does not seem to be mentioned in the CNCF Kubernetes policy mgmt white paper either.

**Comment by hectorj2f** [comment]
I understand your point of view, i have mix feelings about it. For the example for the secret ref, that could probably be done via events. However due to the criticality of our type of policy, I'd vote for failing early (during the creation/update), so users are aware of the policy definition been not configured.

**Comment by vaikas** [comment]
Closing this in favor of:
https://github.com/sigstore/policy-controller/issues/456
