### ISSUE TITLE
What are you wondering about?

### ISSUE THREAD

**Issue by troy256** [sigstore/cosign#1585]
Great project, we are very interesting in using it.  What are the best practices for distributing the public key to end users so they can verify your images?  Thank you!

**Comment by dlorenc** [comment]
There's no simple answer here! That's the hard part of signatures :) It comes down to your exact threat model and where your users are. Fulcio-based keyless signatures simplify this because you don't have to worry about key management, you can just tell your users which email addresses should be used.
