### ISSUE TITLE
Consider changing the Cosigned API ca-key to ca-cert.

### ISSUE THREAD

**Issue by vaikas** [sigstore/cosign#1608]
This comment was not resolved and before going too far down the implementation we should address it:
https://docs.google.com/document/d/1gBLEOOHWOmvHVsoJbgGU74GdwA6CGxMRp3MAeEB50l4/edit?disco=AAAAUEBkXuM

@haydentherapper @mattmoor @coyote240 @hectorj2f @kkavitha @JimBugwadia 

Just adding a few names that have been working on this, feel free to add others. I'm personally +1 on renaming.

**Comment by haydentherapper** [comment]
+1 for this. Referencing the CA certificate instead of the key would be easier when setting up a policy since users won't have to extract the CA key from the certificate. It also means we can make a stronger policy - We're not just enforcing the CA key, but also the CA cert subject, expiration, etc.

I also was wondering what folks thought about making this a list of certificate chains. Currently Sigstore is just a root issuing leafs, but this may not always be the case, if we create an intermediate CA. Additionally, supporting multiple roots would be useful, say if you want to have a policy that supports the Sigstore root and a private root.

**Comment by hectorj2f** [comment]
@haydentherapper @vaikas Yes, it makes sense to me. I am not sure about how common would be to support multiple roots.
