### ISSUE TITLE
Binary for Debian release has unexpected name

### ISSUE THREAD

**Issue by di** [sigstore/cosign#1643]
**Description**

Not entirely sure if this is intentional or not, but I was surprised to find that installing the Debian release (added in #1537) creates a binary named  `cosign-linux-amd64` and not `cosign`.

```
$ docker run -it debian

root@3fe738d1ed8b:/# apt-get update && apt-get install wget
...

root@3fe738d1ed8b:/# wget -q https://github.com/sigstore/cosign/releases/download/v1.6.0/cosign_1.6.0_amd64.deb

root@3fe738d1ed8b:/# dpkg -i cosign_1.6.0_amd64.deb
Selecting previously unselected package cosign.
(Reading database ... 7071 files and directories currently installed.)
Preparing to unpack cosign_1.6.0_amd64.deb ...
Unpacking cosign (1.6.0) ...
Setting up cosign (1.6.0) ...

root@3fe738d1ed8b:/# dpkg -L cosign
/usr
/usr/local
/usr/local/bin
/usr/local/bin/cosign-linux-amd64
/usr/local/bin/cosign-linux-pivkey-pkcs11key-amd64
```

Figured I'd report this in case it was unintentional. Haven't tested any of the other releases from #1537 but this behavior might be present there as well.

(cc @strongjz)

**Comment by dlorenc** [comment]
This is probably a quirk in the goreleaser setup. Agree it's a bug.

**Comment by strongjz** [comment]
I will kook into the templating for the name.  

Looks like `.ConventionalFileName | conventional package file name as provided by nFPM` does just that, copies the name from the build. which is `cosign-linux-{{ .Arch }}` We can probably just use `trimsuffix` to remove anything after the `-`. 

The note/issue for arm version doesn't seem to apply since we specify goarm 7 

https://goreleaser.com/customization/templates/?h=conventionalfilename#fn:9

`Please beware: some OSs might have the same names for different ARM versions, for example, for Debian both ARMv6 and ARMv7 are called armhf. Make sure that's not your case otherwise you might end up with colliding names. `

- https://github.com/golang/go/wiki/GoArm
- https://github.com/goreleaser/goreleaser/issues/36

**Comment by tekumara** [comment]
This is still appears to be the case with v1.7.1 deb:

```
Selecting previously unselected package cosign.
(Reading database ... 212247 files and directories currently installed.)
Preparing to unpack cosign.deb ...
Unpacking cosign (1.7.1) ...
Setting up cosign (1.7.1) ...

~
❯ dpkg -L cosign
/usr
/usr/bin
/usr/bin/cosign-linux-amd64
/usr/bin/cosign-linux-pivkey-pkcs11key-amd64

**Comment by cpanato** [comment]
looks like we changed only the package name but not in binary name inside the package. I think this is not possible to change.

also changing the name broke the release because we now have the same package name for all architectures ( https://github.com/sigstore/cosign/issues/1733 )

**Comment by Dwynie** [comment]
Hi, I have encounter this issue. 

Maybe it will be nice to add the extra steps in the documentation for the new comers.
I renamed the binary folder but I am not sure if it is the right thing to do. Will it be adding complexity for the future upgrade?
