### ISSUE TITLE
[cosigned] image pattern selector: keep glob and remove regex

### ISSUE THREAD

**Issue by hectorj2f** [sigstore/cosign#1834]
**Description**

The ImagePattern field in the ClusterImagePolicy has two optional fields Glob and Regex. There is an internal discussion to remove Regex and keep Glob.

cc @DennyHoang @vaikas @

```
type ImagePattern struct {
	// +optional
	Glob string `json:"glob,omitempty"`
	// +optional
	Regex string `json:"regex,omitempty"`
}
```

**Comment by DennyHoang** [comment]
Currently, globMatch is just a suffix check right now since we support only one wildcard `*`.
That would need to be updated to be actually glob checking before removing regex.

**Comment by adamd-vmw** [comment]
glob has been sufficient for our use cases to date.

**Comment by hectorj2f** [comment]
@DennyHoang Please, create the issue where you explain what is missing in globMatch, so we can fix it.

**Comment by vaikas** [comment]
I think the one problem that can be an issue with glob matching that I've seen personally is when pulling things off of docker.io, sometimes it's index.docker.io for example. And in gcr.io they are sometimes gcr.io, us.gcr.io, asia.gcr.io so for them I think you'd maybe want to create:
*.gcr.io/*
gcr.io/*

instead of listing them all.

**Comment by hectorj2f** [comment]
I am gonna remove the image.regex field now that glob matching has been improved.
