### ISSUE TITLE
Cosigned policies interpreted as regex by default

### ISSUE THREAD

**Issue by znewman01** [sigstore/cosign#1871]
> Unrelated to this PR but it's a regex??? That's a surprise
> 
> Does this open up an attack where someone passes `zjn@mail.example.com` and I go register `mailqexample.com` and can pass the check?

_Originally posted by @znewman01 in https://github.com/sigstore/cosign/pull/1869#discussion_r870839195_

I don't think this is necessarily a problem *except* users shouldn't be surprised by it or do the wrong thing by default. So maybe: make it loudly warn, or make regex behavior configurable? Or support globs instead?

**Comment by znewman01** [comment]
CC @vaikas

**Comment by hectorj2f** [comment]
@znewman01 i am working on using globing and remove regex from the image pattern. There is already an issue

**Comment by znewman01** [comment]
I see #1834...I'm not convinced that this is a dupe, it seems to be a _different_ regex unless I'm misunderstanding something. Would that change make it so that an escaping step happens before we compile it as a regex in `verify.go`?

**Comment by hectorj2f** [comment]
@znewman01 You are right! It is related to https://github.com/sigstore/cosign/blob/main/pkg/apis/cosigned/v1alpha1/clusterimagepolicy_validation.go#L200. For a moment, i believed it was related to #1834.

**Comment by hectorj2f** [comment]
@znewman01  @vaikas Should the subject be a non-regexp instead ? Or you can see use cases here. If so, i am wondering if we should do the same for issuer.

**Comment by znewman01** [comment]
My main concern is that users will *accidentally* enter something like an email (including `.`) which will then be validated in a surprising way.

I'm okay with users *being able to specify* a regex, and it seems useful. Maybe if it's opt-in? Or really obvious (users have to type `r"foo@example.com"` or similar)? I'm not 100% familiar with the context.

**Comment by vaikas** [comment]
Ok. How do folks feel if for v1beta1, we add something like a prefix, r: that indicates it's an regex? It's a bit goofy I suppose, but thoughts?

**Comment by znewman01** [comment]
> How do folks feel if for v1beta1, we add something like a prefix, r: that indicates it's an regex? It's a bit goofy I suppose, but thoughts?

I have one escaping concern long-term: `r:foo@example.com` is a valid email. Though I suppose you could do `r:r:foo@example\.com`—still the same problem of "now `r:foo@example.com` accidentally matches `foo@example.com`. My preference is always going to be to fix this "at the type level".

But yeah something like that would be fine for v1beta1 :)

**Comment by hectorj2f** [comment]
Yeah, let's solve it for v1beta1.

**Comment by vaikas** [comment]
Just bringing this back. So, I think we have couple of options (I'm sure I missed some), but I think I'd rather tackle this hopefully in a more 'final' form sooner rather than later.
Here's few options:
 * Use a re: or some other prefix on the string
 * Create a 'flag' on the `Identity` that controls whether fields are interpreted as RE or not
 * Add SubjectRE and IssuerRE as parallel fields to Subject/Issuer so it's crystal clear that the user is wanting the RE
 
As I said I'm sure there are others, but I think I kind of like the last option for clarity and therefore no confusion on it.
@znewman01 @hectorj2f Thoughts?

And of course, the last option is that we do not allow any regexp at all, but I think it's useful. Maybe I'm wrong :)

**Comment by hectorj2f** [comment]
I definitely agree it is useful, I am just concerned about the prefix `re:` but I don't have a better proposal.
