### ISSUE TITLE
Docker run cosign

### ISSUE THREAD

**Issue by Simkiw** [sigstore/cosign#1904]
Hi team,

I can't install/run my image: gcr.io/projectsigstore/cosign
Although the pull works fine, but when i try to run the instance, as soon as it starts the container and the it's shut down.
This is what I got: ko build ko://github.com/sigstore/cosign/cmd/cosign

Am i doing something wrong or I just can't install cosign using images.

Thank you

**Comment by cpanato** [comment]
Hello, the image is supposed to run one-shot only, like a command line

for example

```
$ docker run gcr.io/projectsigstore/cosign version
  ______   ______        _______. __    _______ .__   __.
 /      | /  __  \      /       ||  |  /  _____||  \ |  |
|  ,----'|  |  |  |    |   (----`|  | |  |  __  |   \|  |
|  |     |  |  |  |     \   \    |  | |  | |_ | |  . `  |
|  `----.|  `--'  | .----)   |   |  | |  |__| | |  |\   |
 \______| \______/  |_______/    |__|  \______| |__| \__|
cosign: A tool for Container Signing, Verification and Storage in an OCI registry.

GitVersion:    v1.8.0
GitCommit:     9ef6b207218572b3257a5b4251418d75569baaae
GitTreeState:  clean
BuildDate:     2022-04-27T13:40:34Z
GoVersion:     go1.17.9
Compiler:      gc
Platform:      linux/arm64
````

I did not understand when you say install, install where? can you elaborate a bit more?
thanks

**Comment by Simkiw** [comment]
Oooooh ok ok ok.

I thought it was something supposed to be running in the background as:
- docker run gcr.io/projectsigstore/cosign **<my_cosign>** (running in the background)
- And then I'll be doing something like **my_cosign version**

And just to make sure I understood well, to be able to use sigstore, I must use each tool separately right? (Cosign, Rekor, Fulcio etc.)

I mean, there is no such a thing as download Sigstore and use it as a one thing (which uses the other tools above).

So yes thanks, it actually works (kinda)

I had this error which I'm still investigating: 

_docker run gcr.io/projectsigstore/cosign generate-key-pair
Enter password for private key: Error: inappropriate ioctl for device
main.go:52: error during command execution: inappropriate ioctl for device_

If you have an idea of why, would be a great, otherwise this issue could be closed (and I'll open another one if I can't figure it out later on)

**Comment by znewman01** [comment]
> And just to make sure I understood well, to be able to use sigstore, I must use each tool separately right? (Cosign, Rekor, Fulcio etc.)

By default, Cosign will talk to the publicly-running instances of Rekor/Fulcio (when `COSIGN_EXPERIMENTAL=1` is on).

> I mean, there is no such a thing as download Sigstore and use it as a one thing (which uses the other tools above).

It is possible to run your own Sigstore (see [Sigstore the Hard Way](https://github.com/lukehinds/sigstore-the-hard-way) and [Sigstore the Local Way](https://blog.chainguard.dev/sigstore-the-local-way/), though this is probably really difficult right now and not what you want in most cases.

> I had this error which I'm still investigating:
> 
> _docker run gcr.io/projectsigstore/cosign generate-key-pair Enter password for private key: Error: inappropriate ioctl for device main.go:52: error during command execution: inappropriate ioctl for device_
> 
> If you have an idea of why, would be a great, otherwise this issue could be closed (and I'll open another one if I can't figure it out later on)

You want `docker run -it gcr.io/projectsigstore/cosign generate-key-pair` (note the `-t`, also known as `--tty`, which lets Cosign see input/output, and `-i`, also known as `--interactive`, which passes through STDIN so you can type a password).

However, this still isn't exactly what you want:

```shell
$ cd $(mktemp -d)
$ docker run -it gcr.io/projectsigstore/cosign generate-key-pair
Enter password for private key:
Enter password for private key again:
Private key written to cosign.key
Public key written to cosign.pub

$ ls
$ # no cosign.key or cosign.pub!
```

This is because it writes these files *inside* the container, which is then cleaned up.

Can I ask why you're trying to use this from the container rather than installing it natively on your OS? The Docker container works great for use cases like GitHub Actions, or any instance when you're not really interacting with the local filesystem. You can use [Docker volumes](https://docs.docker.com/storage/volumes/) to get around this but it's somewhat of a pain and you'll have an easier time just installing Cosign.

**Comment by Simkiw** [comment]
> Can I ask why you're trying to use this from the container rather than installing it natively on your OS?

Of course you can ask of course!

Mostly because I just got into it recently (Docker) and I'm not always comfortable with the releases (should I download the .exe or something else, which version, amd arm stuff like that ...)

Well I'm talking and talking but I already installed the .exe :) as my workaround to be able to try the functionalities of Cosign to begin with, and my goal is to go through the whole process so I can have a general idea of how it works (Sigstore)

> You can use [Docker volumes](https://docs.docker.com/storage/volumes/) to get around this but it's somewhat of a pain and you'll have an easier time just installing Cosign.

Sure and I agree that volumes are not very friendly, I guess, and I might take your advice on using the .exe for simplicity.  
Again, right now I'm more experimenting than implementing. As well as I'll be testing the components separately (Cosign, Fulcio etc.) rather than installing Sigstore as a whole, for simplicity ... again.

Thank you for not only answering my questions, but also for giving additional details illustrated with examples.  
I'm closing the issue, feel free to ask any more questions if intrigued :)
