### ISSUE TITLE
Attestation is not replaced despite success

### ISSUE THREAD

**Issue by chipzoller** [sigstore/cosign#2025]
**Description**

When replacing an attestation of an identical predicate type (keyless), although the command returns success and states the correct predicate type which should be replaced, when verifying attestations afterwards the new attestation is not reflected.

**Version**

1.9.0

**Reproduce Steps**

1. Create, for example, a Trivy scan on a container image that you wish to have attested. See an example workflow [here](https://github.com/chipzoller/zulu/blob/main/.github/workflows/scheduled-scan.yaml) with all this set up.
2. Verify the first attestation is correct.
3. Generate a new scan and replace the existing attestations. It makes no difference if a tag or digest is provided so long as the tag resolves to the same digest.
```
COSIGN_EXPERIMENTAL=1 cosign attest --replace --predicate scan.json --type https://trivy.aquasec.com/scan/v2 ghcr.io/chipzoller/zulu:latest
```
4. Check with `verify-attestations` command and see that the new attestation is not present. If using the sample workflow above, this can be verified by checking the `timestamp` field which should be set to the time at which the scan was performed (roughly).
```
COSIGN_EXPERIMENTAL=1 cosign verify-attestation ghcr.io/chipzoller/zulu:latest | jq -r .payload | base64 --decode | jq > attestationsdecoded.json
```

See full debug logs [here](https://gist.github.com/chipzoller/45387ed2f692679da32efc033a282890).

**Comment by developer-guy** [comment]
Hi @chipzoller, we (w/@dentrax) have investigated this issue. The problem seems related to the `go-containerregistry` lib, In the cosign v1.9.0, which uses `go-containerregistry v0.8.1`. 

We have compiled the cosign binary from the main branch, which uses `go-containerregistry v0.10.0`, and everything worked fine. However, we opened an issue on the zulu project side from installing the cosign binary from the main branch. Would you mind confirming that it is working with it?
> https://github.com/chipzoller/zulu/pull/2

**Comment by Dentrax** [comment]
Hey @cpanato! 👋 

Is it good time to release cosign 1.9.1? There are more than [350+ changes](https://github.com/sigstore/cosign/compare/v1.9.0...main) since last release. Obviously, bumping `go-containerregistry` is the major one. Also there some good ones such as bumping Go to 1.18, env subcommand, cyclonedx support, cert-extensions verify, etc. Wdyt?

**Comment by cpanato** [comment]
1.10.0 release is out https://github.com/sigstore/cosign/releases/tag/v1.10.0

**Comment by chipzoller** [comment]
Confirmed working using Cosign 1.10.0! Nice work, everyone!

**Comment by chipzoller** [comment]
Closed in PR https://github.com/sigstore/cosign/pull/2021, verified in release 1.10.0.
