### ISSUE TITLE
Are secure timestamps omitted intentionally?

### ISSUE THREAD

**Issue by luc-lynx** [sigstore/cosign#2098]
**Question**

Having a quick look at the signature process I can't see any queries to secure timestamping services. Including a signed timestamp is a critical piece of functionlity for almost any scenario involving digital signatures. 

There's a citition from the [cosign course on Edx](https://learning.edx.org/course/course-v1:LinuxFoundationX+LFS182x+2T2022/home)

> Because these keys persist only long enough for signing to take place, signature verification ensures that the certificate was valid at the time of signing.

If a signature is valid it's impossible to guarantee that the key wasn't expired at the time of signing without usage of signed timestamps from third party. In other words, if I compromised an expired "keyless" key pair, what prevents me from signing another payload and claiming that the signature is valid?

Upload to transparency log can help to reveal cheating with signatures, but at the time of writing there're no checks for consistency of subsequent log entries in transparency log e.g. that an entry is older than a pervious one. 

So, my questions are:
- what is the protection from using expired "keyless" pairs and claiming that signatures are valid?
- what is the design rationale for not including signed timestamps into signatures like it's done in MS Authenticode?

**Comment by dlorenc** [comment]
> * what is the protection from using expired "keyless" pairs and claiming that signatures are valid?

We use the transparency log (Rekor) inclusion proof as a timestamp. It serves the same purpose but has a different API than traditional TSA's.

I would like to add support for RFC3161 TSAs in addition. 

There's some discussion here: https://blog.sigstore.dev/its-ten-o-clock-do-you-know-where-your-private-keys-are-5c869cf53234

**Comment by asraa** [comment]
> consistency of subsequent log entries in transparency log e.g. that an entry is older than a pervious one.

Agreed, there is no monitoring that verifies monotonicity of the integrated time in Rekor. Even then, the integrated time in an entry can be mutated in the underlying database. There's also no way of adding an external or third party timestamp in our APIs, with either an RFC 3161 timestamp or other timestamping protocols.

I agree that there is room to add this data into Rekor entries in a variety of ways, to allow clients to have some external verification besides trust in Rekor and its database.

> what is the protection from using expired "keyless" pairs and claiming that signatures are valid?

Right now as Dan mentioned, the protection is coming from using the integrated time of the entry as a proxy for when the signature was created (the sig is part of the entry). 

See also https://github.com/sigstore/rekor/issues/824, @haydentherapper is moving the timestamper into a separate repo, where we can host a TSA.

**Comment by asraa** [comment]
> Upload to transparency log can help to reveal cheating with signatures, but at the time of writing there're no checks for consistency of subsequent log entries in transparency log e.g. that an entry is older than a pervious one.

One more addition: Rekor supports an RFC 3161 timestamp type, which means you can upload timestamps on a cron or scheduled job to Rekor for more assurance of its integrated time. That can provide some guarantees that entries are monotonic in relation to those timestamps.

**Comment by luc-lynx** [comment]
> the protection is coming from using the integrated time of the entry as a proxy for when the signature was created (the sig is part of the entry)

Can you elaborate on that? I'm just trying to understand the security guarantees. Let's assume I rely only on the project tooling without additional code written and additional checks performed on my side - just using cosign sign/sign-blob, cosign verify with support for rekor checks (experimental enabled) and funcio "keyless" scheme like it's suggested in various posts, documentation and EDX course. 

From my perspective the process can guarantee the following: _the signatures are trusted as long as all the signing keys have never been compromised despite the expiration time_.

If any of the signing key pairs used was compromised - I cannot trust the root any longer (seems weird, but I need a revokation mechanism for expired keys), because the only way to stop the attack is to remove trust from root key. 

This eliminates the advantages of using fulcio and "keyless" signing scheme and gets us back to the security guarantees similar to static pub/priv key pair.

Am I right?

**Comment by haydentherapper** [comment]
Walking through the signing and verification flow, focusing on where timestamps are referenced:

On signing:

1) Fulcio creates a short-lived certificate, associating an identity with an ephemeral public key
2) The certificate is uploaded to a transparency log along with the signature and artifact hash
3) The log returns a signed bundle which includes the inclusion timestamp and artifact hash, and this is persisted with the certificate and signature (you can also ask the log for a proof of inclusion)

On verification:

1) The Fulcio certificate's signature is verified from Sigstore's root of trust (shipped with Cosign), and ignoring time
2) The log presents the inclusion time of the entry, either from the signed bundle or requesting it from the log <-- We'll come back to this step
3) A verifier checks that the inclusion time is before the certificate's expiration time. If so, then the verifier knows that the certificate was valid when the artifact was signed, so we can trust the certificate, and therefore trust the ephemeral public key to verify the artifact signature.

Step (2) of verification relies on the log to give you the inclusion time. That time is currently not signed by the log, so it could be mutated by a log operator without detection, which would result in a denial of service effectively, since certificates would not be considered valid. This can be mitigated by uploading signed timestamp entries, and we're also working on solving this with other timestamp formats too.

**Comment by asraa** [comment]
> the signatures are trusted as long as all the signing keys have never been compromised despite the expiration time.

Note that you are still correct here: the expiration time is about 10 minutes, and a compromised key that re-uses the signing cert and signs during that 10 min window would still validate. Keyless attempts to have a small enough window where compromise is feasible compared to std PKI

**Comment by luc-lynx** [comment]
Thank you all for the explanation, now it's clear!

**Comment by asraa** [comment]
Closing because all clear!
