### ISSUE TITLE
Attached Signatures

### ISSUE THREAD

**Issue by dlorenc** [sigstore/cosign#211]
Right now we only work with detached signatures for containers. This handles most workflows fine. We may also want to consider adding support for attached signatures. The downside is that these mutate the container image, but people may still prefer them.

One UX could be:

`cosign sign --attach` (does the same thing it does now, but stores the signatures on the image itself)
`cosign attach` this attaches all the signatures from their normal location (`cosign triangulate`) to the specified image, resulting in a new digest.

**Comment by priyawadhwa** [comment]
I guess verify would do the following in this case:
 -  Take in the attached image name and the original image name
 -  Make sure the digests of the layers between the original and the attached images match (except for the extra signature layer we added)
 -  Verify the signature in the extra layer in the attached image against the original image

We could also add the old image name as an annotation in the attached image so that users don't have to pass both of them in?

**Comment by dlorenc** [comment]
Yeah I think that's all we could really do... I don't love it...

**Comment by dlorenc** [comment]
I don't think we can really do much here, closing unless there's a lot more demand.
