### ISSUE TITLE
docker pull - failed to register layer: Error processing tar file(exit status 1): unexpected EOF

### ISSUE THREAD

**Issue by gerhard** [sigstore/cosign#2298]
### How to reproduce

```
❯ docker pull ghcr.io/sigstore/cosign/cosign:sha256-a9664c77caafbc0e6d94b6023ebff26fcfaa30fc763c573b241e33c60398dfec.sig
sha256-a9664c77caafbc0e6d94b6023ebff26fcfaa30fc763c573b241e33c60398dfec.sig: Pulling from sigstore/cosign/cosign
e759d0bcbc8c: Extracting [==================================================>]     332B/332B
failed to register layer: Error processing tar file(exit status 1): unexpected EOF
```

### How to workaround

```
❯ docker pull gcr.io/projectsigstore/cosign:v1.12.1@sha256:ac8e08a2141e093f4fd7d1d0b05448804eb3771b66574b13ad73e31b460af64d
gcr.io/projectsigstore/cosign@sha256:ac8e08a2141e093f4fd7d1d0b05448804eb3771b66574b13ad73e31b460af64d: Pulling from projectsigstore/cosign
1cd0595314a5: Pull complete
bf75762436b0: Pull complete
ae475359a3fb: Pull complete
250c06f7c38e: Pull complete
f92a87f81fe6: Pull complete
Digest: sha256:ac8e08a2141e093f4fd7d1d0b05448804eb3771b66574b13ad73e31b460af64d
Status: Downloaded newer image for gcr.io/projectsigstore/cosign@sha256:ac8e08a2141e093f4fd7d1d0b05448804eb3771b66574b13ad73e31b460af64d
gcr.io/projectsigstore/cosign:v1.12.1@sha256:ac8e08a2141e093f4fd7d1d0b05448804eb3771b66574b13ad73e31b460af64d
```

### `docker info`

```
❯ docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., 0.0.0+unknown)
  compose: Docker Compose (Docker Inc., 2.5.1)

Server:
 Containers: 10
  Running: 4
  Paused: 0
  Stopped: 6
 Images: 8
 Server Version: 20.10.17
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: journald
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: v1.6.4
 runc version:
 init version:
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.15.58
 Operating System: NixOS 22.05 (Quokka)
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 62.72GiB
 Name: x22
 ID: A3L5:E7A2:DYTT:WAZD:IF5J:CM53:6BKQ:LH2F:ZW5J:I557:MQDR:JIEQ
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: gerhard
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: true
```

**Comment by ChristianCiach** [comment]
That is probably expected...? Cosign signature images are not in a usual format that Docker could handle. In fact, the integrated Trivy scanner for our Harbor registry chokes similarly:

![grafik](https://user-images.githubusercontent.com/19341644/193884655-e3ab443a-38b6-43cf-8adb-16cb290c930d.png)

When I click on "View logs" the log says:
```
image scan error: scan error: image scan failed: failed analysis: analyze error: failed to analyze layer: sha256:6535572bb4db769acd49b16cce0335166bad95c0e41680992a7bd9f1302ae717 : walk error: failed to extract the archive: archive/tar: invalid tar header
```

I don't think this is a bug. Tools like Docker and Trivy just don't know how to handle this format.

**Comment by richlander** [comment]
I also noticed this. I wonder why the default experience using cosign if it isn't compatible with `docker pull`.

https://github.com/actions/starter-workflows/blob/main/ci/docker-publish.yml

**Comment by znewman01** [comment]
> I don't think this is a bug. Tools like Docker and Trivy just don't know how to handle this format.

Precisely. This is expected behavior and IMO not a real problem. What *should* happen when you try to `docker pull` something that's not an image? If anything, this is a bug for docker to give you a better error message.

For background, those are OCI objects containing signatures, *not* images. They're given a tag like  to aid in discoverability: the signatures on an image `gcr.io/foo@sha256:abcdef` would be stored at `gcr.io/foo:sha256-abcdef.sig`. [Until recently](https://github.com/opencontainers/wg-reference-types), there was no other good way to store metadata that *references* an artifact on an OCI registry, so it's a bit of a hack. Within the past month or so, there was [an update to the OCI spec that allows this](https://github.com/opencontainers/wg-reference-types); we're tracking moving cosign to support this in 
https://github.com/sigstore/cosign/issues/1397 .

You can use a tool like [`crane`](https://github.com/google/go-containerregistry/blob/main/cmd/crane/doc/crane.md) to inspect the signature:

```
$ crane manifest ghcr.io/sigstore/cosign/cosign:sha256-a9664c77caafbc0e6d94b6023ebff26fcfaa30fc763c573b241e33c60398dfec.sig
```

But to be perfectly honest, you probably just want to *validate* the image directly rather than trying to look at its signature yourself:

```
$ COSIGN_EXPERIMENTAL=1 cosign verify ghcr.io/sigstore/cosign/cosign@sha256:a9664c77caafbc0e6d94b6023ebff26fcfaa30fc763c573b241e33c60398dfec
```

> I also noticed this. I wonder why the default experience using cosign if it isn't compatible with `docker pull`.
>
> https://github.com/actions/starter-workflows/blob/main/ci/docker-publish.yml

I don't quite understand your point. To me, that's somewhat analogous to asking "why would you GPG sign a Python package if the `python` binary can't execute the GPG signature?"


It's very possible that the work in https://github.com/sigstore/cosign/issues/1397 will make this error a little bit more obvious.

**Comment by znewman01** [comment]
I'm going to close for now; please reopen if you think there's something we can do on our end to make this better!

**Comment by gerhard** [comment]
Great answer @znewman01, all clear now, thank you!
