### ISSUE TITLE
Verify the binary downloads when installing from .deb (or any other binary release)

### ISSUE THREAD

**Issue by nicolaevladescu** [sigstore/cosign#2300]
How can we verify the binary downloads when installing from .deb?

Can the downloads be verified with openssl or gpg?

It's kind of an chicken and egg problem if you use `cosign` to sign blobs, you assume there is a `cosign` version already on the system, but in my case it is not.

**Comment by znewman01** [comment]
If I understand correctly, you're saying: why should I trust the .deb files (and other release artifacts) coming from the Cosign repository on GitHub itself.

This is a pretty interesting question, glad you asked it :)

I can think of three broad approaches:


1. Provide alternate signatures (e.g., using GPG).
2. Provide instructions for performing Cosign verification manually. There's nothing magic about Sigstore, and you can cobble together everything it does from openssl (ex. [sigstore the bash way](https://gist.github.com/bobcallaway/e669534a9591c802b64c84603323c2c0)).
3. Distribute Cosign over some existing secure channel. In some sense, if you're downloading over TLS, you're already doing this. But this could also refer to downloading Cosign from the official Ubuntu repositories, where it will be signed.

IMO (1) and (2) are actually misleading: if you don't have Cosign on your system, you probably don't already have the keys used to sign the Cosign releases on your system. So even if you could use GPG to verify, if you're just pulling the GPG key from the same place you're downloading Cosign you're not really gaining any security since an attacker who could replace the Cosign binary could also replace the purported signing key. You have to take a leap of faith at some point, and it's nice to do (3) and at least tie your trust in Cosign back to something *else* you're already trusting.

You might be able to do something convoluted that looks something like [diverse double compiling](https://dwheeler.com/trusting-trust/). You as a client download Cosign and an alternate Sigstore implementation from another organization, and use them to verify each others' signatures. But the problem of "what keys should you check the signatures against" is left unanswered still. 

You could also try to rebuild the .debs yourself from source and see if they match ([reproducible builds](https://reproducible-builds.org/)). But this just kicks the question up one level: how do you know the source is legitimate?

I suppose what I'm saying is that I'm somewhat nihilistic about this whole process and I recommend you just consider the initial Cosign download to be the root of trust for the system. If that's unacceptable in your threat model, you're going to have to do something way more elaborate than we can help with.

**Comment by nicolaevladescu** [comment]
> If I understand correctly, you're saying: why should I trust the .deb files (and other release artifacts) coming from the Cosign repository on GitHub itself.
> 
> This is a pretty interesting question, glad you asked it :)
> 
> I can think of three broad approaches:
> 
>     1. Provide alternate signatures (e.g., using GPG).
> 
>     2. Provide instructions for performing Cosign verification manually. There's nothing magic about Sigstore, and you can cobble together everything it does from openssl (ex. [sigstore the bash way](https://gist.github.com/bobcallaway/e669534a9591c802b64c84603323c2c0)).
> 
>     3. Distribute Cosign over some existing secure channel. In some sense, if you're downloading over TLS, you're already doing this. But this could also refer to downloading Cosign from the official Ubuntu repositories, where it will be signed.
> 
> 
> IMO (1) and (2) are actually misleading: if you don't have Cosign on your system, you probably don't already have the keys used to sign the Cosign releases on your system. So even if you could use GPG to verify, if you're just pulling the GPG key from the same place you're downloading Cosign you're not really gaining any security since an attacker who could replace the Cosign binary could also replace the purported signing key. You have to take a leap of faith at some point, and it's nice to do (3) and at least tie your trust in Cosign back to something _else_ you're already trusting.
> 
> You might be able to do something convoluted that looks something like [diverse double compiling](https://dwheeler.com/trusting-trust/). You as a client download Cosign and an alternate Sigstore implementation from another organization, and use them to verify each others' signatures. But the problem of "what keys should you check the signatures against" is left unanswered still.
> 
> You could also try to rebuild the .debs yourself from source and see if they match ([reproducible builds](https://reproducible-builds.org/)). But this just kicks the question up one level: how do you know the source is legitimate?
> 
> I suppose what I'm saying is that I'm somewhat nihilistic about this whole process and I recommend you just consider the initial Cosign download to be the root of trust for the system. If that's unacceptable in your threat model, you're going to have to do something way more elaborate than we can help with.

Hello.

I see 1. and 2. almost the same option and the only wide spread one,  it should not be anything complicated, lots of project that sign their binary releases already distribute a key and use `gpg` to verify. An imprefect remedy to the trusting of the key problem is to get only the public key id from cosign and the look it up on a public PGP server.

**Comment by znewman01** [comment]
> I see 1. and 2. almost the same option and the only wide spread one, it should not be anything complicated,

Agreed, it would be pretty easy to do. But I think we want to avoid anything that presents a false sense of security.

> lots of project that sign their binary releases already distribute a key and use gpg to verify.

In my experience, "lots of projects already do it" is not a strong signal that a security practice is worthwhile 🙂 

> An imprefect remedy to the trusting of the key problem is to get only the public key id from cosign and the look it up on a public PGP server.

Can you elaborate on this workflow? What would I be checking when I look it up on a public PGP server—that I personally know a Cosign developer? One of the primary premises of the Sigstore project is that web-of-trust is an inappropriate security model for software distribution, and I think that holds here as well.


----------------------------------------------------------------

I think we'd be willing to sign with a long-lived key if there was a concrete scenario that it helped with, security-wise or the user experience was really good. The real problem is that I haven't been convinced that there are many scenarios where GPG verification is substantially better than trust-on-first-use with Cosign used directly for later verification. Here are a few:

- A downstream maintainer (e.g., a Debian packager) wants a long-lived key with which to verify new Cosign releases that they repackage, but aren't ready to use Cosign directly for that purpose.
- GPG keys have better integration with the tooling users use to , so users will *actually* check updates . I think an apt repository that we manage would be a good example here.

Otherwise, I think we can just provide instructions for verifying the existing signatures using tools *other* than Cosign. This means we get essentially the same security model as GPG (trust on first use, and you can try to verify keys out of band if you want, though in practice nobody will) but also get the transparency benefits of using Sigstore (any package artifacts not corresponding to the repo source will be detected).

-------------------------------------------------------------

I'm just one person and I don't represent the Sigstore project, so you don't have to convince me 😄 . But you do have to convince other members of the Sigstore community that the reward here is worth the effort. My thoughts here have been largely informed by [this blog post](https://caremad.io/posts/2013/07/packaging-signing-not-holy-grail/) and this [related issue for PyPI](https://github.com/pypi/warehouse/issues/3810) and I'm generally skeptical of package signing without hooking up to a bigger root-of-trust.

**Comment by znewman01** [comment]
BTW I hope I'm not coming off as hostile! We're very open to this idea, but we just want to understand concretely what the benefits are to GPG signing before we go through the effort of implementing it.

**Comment by nicolaevladescu** [comment]
I agree with all your points, and yes, lots of projects doing something doesn't make it bulletproof or worth implementing just for the sake of it. It was just a reflex of mine to always try to do some additional checks when downloading something from the internet in my CI/CD workflows.

The trust-on-first-use with Cosign is not that different versus trusting a distro release released with gpg already installed or a package and an official repository (implicitly also trusting the repository maintaners), and then trusting a PGP server and a public key while getting the public key id from exactly the same place where you can get Cosign itself. You would essentialy move the trust-on-first-use scenario futher upstream and add additional steps and unwated complexity for no actual security gain.

Thank you, i am closing the issue.
