### ISSUE TITLE
cosign attach multiple SBOM

### ISSUE THREAD

**Issue by ep4sh** [sigstore/cosign#2508]
Dear community, 

could you please explain how to attach multiple sboms with cosign and sign them (in different format `spdx` and `cyclone-dx` for instance)?

thanks you in advance,
Pasha.

**Comment by developer-guy** [comment]
AFAIK, there is no way of attaching multiple SBOMs at once but you can basically run the `cosign attach` command twice with keyed or keyless approaches for a different types of SBOM formats. PTAL @hectorj2f

**Comment by developer-guy** [comment]
But it would be a pretty easy task to do. We can provide such a feature for attaching multiple SBOMs at once by guessing the types, PTAL @dlorenc. Because the feature that exists in cosign for attaching multiple attestations is stored in the JSONLines file, which is a format for storing various attestations, @puerco is there any form that exists for storing multiple SBOMs?

**Comment by ep4sh** [comment]
👀 👀 👀

**Comment by hectorj2f** [comment]
You could create a single SBOM and add references to others. I won't recommend to attach one included all. Why cannot you add them separately or as i mentioned here?

**Comment by hectorj2f** [comment]
Obviously I'll avoid mixing formats.

**Comment by rllane17** [comment]
hi
