### ISSUE TITLE
Multiple warnings during the SBOM signing

### ISSUE THREAD

**Issue by ep4sh** [sigstore/cosign#2526]
**Question**

Dear community,
I'm facing an issue (Warning) when attaching and signing SBOM to the container image.
The first part is like that:
```
WARNING: Attaching SBOMs this way does not sign them.
 If you want to sign them, use 'cosign attest --predicate /builds/<REDACTED>_4.5.1-0_spdx.json --key <key path>' or 'cosign sign --key <key path> --attachment sbom <image uri>'.

Uploading SBOM file for [index.docker.io/<REDACTED>@sha256:8ebb8b6515a96df75a48c993e27de45e985ddf9f130de8c63ae599711710c6f9] to [index.docker.io/<REDACTED>:sha256-8ebb8b6515a96df75a48c993e27de45e985ddf9f130de8c63ae599711710c6f9.sbom] with mediaType [spdx+json].
```
As far I understood, it is just a notification to not forget to sign SBOM separately.

Then I get this:
```
WARNING: Image reference <REDACTED>:sha256-8ebb8b6515a96df75a48c993e27de45e985ddf9f130de8c63ae599711710c6f9.sbom uses a tag, not a digest, to identify the image to sign.
```
I'm not sure if I fully understand it, if it's possible, could somebody explain what that means.

The commands I'm using to sign SBOM:
```
    export IMAGE_NAME=<REDACTED>:${IMG_TAG}
    docker pull ${IMAGE_NAME}
    export IMAGE_DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' $IMAGE_NAME) # for image sign
    export IMAGE_URI=$(echo $IMAGE_DIGEST | sed -e 's/\@sha256:/:sha256-/') # for SBOM sign
    ......
    ......
    ......
    cosign sign --key env://COSIGN_PRIVATE "$IMAGE_URI.sbom"

```

PS: the docs I used to accomplish it:
https://docs.sigstore.dev/cosign/other_types/#sboms-software-bill-of-materials

thank you in advance,
Pasha

**Comment by developer-guy** [comment]
Hello @ep4sh, thx for raising an issue! You don't need to sign your SBOM directly; however, you can though 🤔, but you don't need to; you can sign the digest of an image that points to an SBOM because the SBOM you are about to attach is going to be stored as a separate tag of the same image which means that the digest of it will be different and also this will be the digest that you are going to sign. PTAL @znewman01 ☝️

**Comment by znewman01** [comment]
CC @asraa

**Comment by ChristianCiach** [comment]
I am not a fan of the first warning, too. This is why I created issue https://github.com/sigstore/cosign/issues/2307

I think their should be at least one of these two options:
* A way to create/download and sign/verify an SBOM at the same time to suppress this warning. See https://github.com/sigstore/cosign/issues/2307#issuecomment-1267061747
* A simplier way to retrieve the original SBOM from an in-toto attestation. See https://github.com/sigstore/cosign/issues/2307

As things currently are, we don't want to use attestations because it is just too cumbersome to extract the SBOM from it. But at the same time we don't like to scare users who try to validate our images. 

If cosign wants to discourage or soft-deprecate `cosign [download|attach] sbom` (and I think this is what cosign is currently doing), then I think there should be another command that procuces the exact same output as `cosign download sbom` from an attestation.

**Comment by znewman01** [comment]
@ChristianCiach thanks for the context! I think I'm going to close this out in favor of #2307. I think those suggestions will address this issue.
