### ISSUE TITLE
Keep the signature attached to the payload, not in the index

### ISSUE THREAD

**Issue by MarkLodato** [sigstore/cosign#264]
Currently, cosign splits the attestation in two separate blobs: the `signature` is stored inside the index and the unsigned `payload` is stored as a blob in the CAS. (The `payload` in turn contains the hash of the thing-to-be-signed.)

In my opinion, this design is a mistake:

- It unnecessarily ties the storage to the crypto. In order to store a signed message into the registry, the tool has to understand the format, parse it, and stick the bits in the right spot. This is both added complexity and reduced utility.
- It prevents standard attestation tooling from working (unless you translate back to the original format). These tools take a signed message as a unit.
- It encourages mistakes by making it way too easy to forget to verify the signature. The payloads MUST NOT be used on their own, yet the design does nothing to safeguard against such a mistake.

I don't understand the [rationale](https://github.com/sigstore/cosign/blob/main/SPEC.md#hash-algorithm---none) given for this design (emphasis mine):

> This is only possible if we store the `payload` in a blob by itself. Serializing the payload and signature together in something like a JWT for storage would mean the **payload is no longer directly hashed into the CAS**. There is also a performance benefit: **we can validate the signature (stored in the manifest) against the payload (stored as a blob) without fetching the blob**, because the blob's digest is also present in the manifest.

- What is the benefit of having the payload hashed into the CAS? The payload by itself is not meaningful, and using it without verifying the signature is a security mistake (noted above).
- What is the use case for verifying the signature of the payload itself, without knowing the thing-to-be-signed?

 It would be more natural to have to independent layers:

- How to associate one blob with another within an OCI Registry (via the clever hash-tag idea). Nothing to do with crypto.
- How to sign metadata about one or more software artifacts (such as the [in-toto attestation](https://github.com/in-toto/attestation/)).

**Comment by dlorenc** [comment]
What standard attestation tooling?

I think most of this feedback is really addressed as: cosign isn't really designed for "attestations". Cosign signs containers, which has value on its own. I think the simplicity actually reduces our attack surface, see the design inspiration section on tools like minisign/signify.

Cosign signs and verifies containers, not arbitrary attestations today, and that's really all it's aiming to do right now. This is mostly based off the polling info here and from conversations on what people are trying to do today: https://twitter.com/samuelkarp/status/1305625523779903489?s=19

We can sign other attestations as well, and many of these concerns would apply there, but that not really in scope right now.

The "escape hatch" of "cosign sign -payload" is already in place for users that want to use cosign as just a storage mechanism. The full flow to sign and attach arbitrary payloads (could be a predicate, or anything else) would be:

cosign sign -payload foo
cosign verify --claims=false

Or if you don't want to use the crypto:

cosign upload -payload foo
cosign fetch image

We can change flag names but this is the intended layering. You can use any of the combinations today:

* Storage, crypto, lightweight claims (key value pairs)
* Storage, crypto, bring your own payload format
* Just storage, bring your own crypto and payload format
* Storage and claims, bring your own crypto
* Crypto and claims, bring your own storage, etc.

I think the annotatIon values are really the only thing a user could "forget" to verify. So if the current behavior ends up being too error prone, I'd prefer we reduce scope by removing the support for claims (the -a flag) rather than adding complexity.

You could of course forget to verify the image digest itself, but that would apply to any detached signature schemes and is roughly equivalent to just ignoring the signature completely. If that turns out to be an issue then I'd rather we drop the JSON wrapper completely and literally only sign the digest bytes.

**Comment by dlorenc** [comment]
> * It unnecessarily ties the storage to the crypto. In order to store a signed message into the registry, the tool has to understand the format, parse it, and stick the bits in the right spot. This is both added complexity and reduced utility.

I'm not sure I follow - cosign doesn't parse payloads during signing - it generates them. 

> * What is the benefit of having the payload hashed into the CAS? The payload by itself is not meaningful, and using it without verifying the signature is a security mistake (noted above).

It's spelled out in the section you quoted - we can verify the signature without even needing to download, parse or display the payload. The interface of cosign requires users to validate signed payloads against a specified public key. We can avoid needing to download, parse and verify embedded claims for payloads that don't even pass initial signature/public key validation.

> * It encourages mistakes by making it way too easy to forget to verify the signature. The payloads MUST NOT be used on their own, yet the design does nothing to safeguard against such a mistake.

I'd actually argue the opposite. I can't see how you would make this mistake today. The index only contains the signature and the signed hash, not the raw payload. You need to look at this tuple (signature, signed hash) to even find where the payload is stored in the CAS before making a series of network requests to fetch it.

I can't force users to verify the signature here, but it's impossible to even find the address of the payload and its contents without first fetching and reading the signature. Sure, they could simply ignore and discard it, but the same is true of any other detached signature format.

**Comment by MarkLodato** [comment]
Sorry, I used the term "attestation" too loosely. The issue is independent of "in-toto attestations" vs the regular signatures you are producing. I just need a term other than "signature" because there is the actual signature bytes (output of the crypto primitive) and the overall scheme (including the simple-signing payload).

> It's spelled out in the section you quoted - we can verify the signature without even needing to download, parse or display the payload.

Can you provide a concrete example? The documentation is inconsistent (it calls both Payload and Manifest below `payload`), but I think this is how it works (omitting irrelevant fields):

- Digest of the container image to be signed: `sha256:aaaaaaaa`
- Payload, with digest `sha256:bbbbbbbb` (stored in the CAS)
  ```json
  {"critical": {"image": {"Docker-manifest-digest": "sha256:aaaaaaaa"}}}
  ```
- Manifest, with digest `sha256:cccccccc` (stored in the CAS)
  ```json
  {"layers": [{
    "mediaType": "application/vnd.dev.cosign.simplesigning.v1+json",
    "digest": "sha256:bbbbbbbb",
    "annotations": {"dev.cosignproject.cosign/signature": "xxxxxxxx"}
  }]}
  ```
- Tag: `sha256-aaaaaaaa.cosign`, which points to `sha256:cccccccc`

IIUC, you are saying that you can verify that `xxxxxxxx` verifies over `sha256:bbbbbbbb` without fetching the payload. But why would you want to do that? That is very error prone. It doesn't validate that `sha256:bbbbbbbb` actually refers to the container image `sha256:aaaaaaaa`.

A much more natural solution would be to move the signature to the payload:

- Digest of the container image to be signed: `sha256:aaaaaaaa`
- Payload, with digest `sha256:bbbbbbbb` (stored in the CAS)
  ```json
  {"payload": "<base64 encoding of payload referencing sha256:aaaaaaaa", "signature": "xxxxxxxx"}
  ```
- Manifest, with digest `sha256:cccccccc` (stored in the CAS)
  ```json
  {"layers": [{
    "mediaType": "application/vnd.dev.cosign.signed-message.v1+json",
    "digest": "sha256:bbbbbbbb",
  }]}
  ```
  Note: no signature here.
- Tag: `sha256-aaaaaaaa.cosign`, which points to `sha256:cccccccc`

>> It unnecessarily ties the storage to the crypto. In order to store a signed message into the registry, the tool has to understand the format, parse it, and stick the bits in the right spot. This is both added complexity and reduced utility.
>
> I'm not sure I follow - cosign doesn't parse payloads during signing - it generates them.

Suppose GitHub Actions produces a container image `sha256:aaaaaaaa` and a signature over that image. The signature will be written to some file containing both the `signature` and the `payload` (which in turn references `sha256:aaaaaaaa`). Let's call this file the "envelope".

With cosign's current storage mechanism, you need to:
- Parse the envelope, pull out the `signature`, and decode `payload`.
- Upload the decoded payload to the CAS.
- Update the manifest for `sha256:aaaaaaaa` to reference the payload blob AND add the `signature` as an annotation.

With my proposal, you don't have to understand the format at all:
- Upload the envelope to the CAS.
- Update the manifest for `sha256:aaaaaaaa`to reference the envelope blob.

**Comment by dekkagaijin** [comment]
> IIUC, you are saying that you can verify that xxxxxxxx verifies over sha256:bbbbbbbb without fetching the payload.

Stated another way, keeping the sig in the index allows us to verify the signed payload _before_ fetching it (not _without_ fetching it).

**Comment by MarkLodato** [comment]
> Stated another way, keeping the sig in the index allows us to verify the signed payload _before_ fetching it (not _without_ fetching it).

But what value does that provide? Isn't the expected case that they all pass, thus in practice you'll always end up fetching it?

**Comment by dlorenc** [comment]
This is now supported with "cosign attest". Closing here.
