### ISSUE TITLE
sget alternative to download artifact from OCI registry and verify it.

### ISSUE THREAD

**Issue by chunteck** [sigstore/cosign#2754]
Following the "Working with Blobs" documentation on sigstore here: https://docs.sigstore.dev/cosign/working_with_blobs/

As per the documentation, we can `cosign upload blob` to place an artifact in the registry and sign it, and subsequently use `sget` to verify it later.

It seems like the `sget` command in cosign is going to be deprecated soon, and the new `sget` repo (https://github.com/sigstore/sget) does not seem to be able to able to perform the download and verification of the artifact using an image tag. The `--key` option is not available in the new `sget` and the new `sget` only supports downloading the artifact from the registry using a digest (without verification)

Is there an alternative to `sget`, or are there future plans to add this functionality back into the new `sget`? Are there any other `cosign` commands that can be used to download + verify an artifact from the registry using the image tag?

**Comment by znewman01** [comment]
This is something we should support directly in Cosign, rather than sget. Overall we're trying to unwind the coupling between the OCI and Sigstore-infra aspects of various Sigstore projects, with OCI stuff living in Cosign.

You can achieve this via

```
DIGEST=$(crane digest $IMAGE)
cosign verify $DIGEST && crane download $IMAGE
```

Right now. 

It's a good idea though. We could make an extension to the `cosign download` command.
