### ISSUE TITLE
Question: what URI schemes can be used with cosign?

### ISSUE THREAD

**Issue by fpoirotte** [sigstore/cosign#2783]
**Question**

Hi, I'm trying to use cosign through [syft](https://github.com/anchore/syft/) to generate and attach an SBOM attestation to a local image generated by podman.
While syft can create the SBOM just fine, it errors out when calling cosign because it passes a podman reference (`podman:localhost/test:0.0.0`) to cosign.

Is this supposed to work?

The doc for [cosign attest](https://github.com/sigstore/cosign/blob/main/doc/cosign_attest.md) states that an "image uri" must be passed, but does not specify what URI schemes are actually supported.

FWIW, I opened a bug report against syft in relation with this question : https://github.com/anchore/syft/issues/1664

**Comment by znewman01** [comment]
CC @sudo-bmitch is there a standard for image references here?

I'm pretty sure we just pass this to [go-containerregistry ParseReference](https://pkg.go.dev/github.com/google/go-containerregistry@v0.13.0/pkg/name#ParseReference). IIUC `localhost/test:...` should work.

**Comment by sudo-bmitch** [comment]
At this point, not yet. I'd like to see some kind of scheme prefix, like `type://` defined by OCI. But for now, just the parsing of a reference to an image in a registry as a standard in OCI is in the backlog, we're all using code from docker as our example to copy in each implementation, and anyone extending that has picked a different syntax.

With the podman example, I'm not sure how well that would work cosign, because it's putting non-image data into a container runtime. Support for that is going to get specific to each runtime.

There is an on-disk format for storing images called the OCI Layout, but just adding more than one platform is enough to break most tools. Adding a second tag for the SBOM or signature will be even less supported. It's an area where we still have a lot of work to do with all the tooling.

**Comment by znewman01** [comment]
Thanks, that's super-helpful context. Sounds like better docs here would be very helpful in the short run. 

What's the right thing to here? Add explicit support for podman? Sounds like that might a little bit more work than just getting the image reference right. We could do a pretty simple test where we just strip the `podman:` prefix, though that's probably not the right move long-run.
