### ISSUE TITLE
Blob usage - cosign & oras

### ISSUE THREAD

**Issue by lmussier** [sigstore/cosign#2859]
**Question**
Hi,

I have a question related to the upload blob feature.
I'm trying to upload something before signing it, and I get weird behaviour when trying to simply get the artifact back.

```
lmussier@lmussier-vm:/tmp$ cosign upload blob -f artifact ghcr.io/lmussier/artifact:cosign
Uploading file from [artifact] to [ghcr.io/lmussier/artifact:cosign] with media type [text/plain]
File [artifact] is available directly at [ghcr.io/v2/lmussier/artifact/blobs/sha256:727e12e4935c52ba62c9ffb79dc37335436eed46dc0eb6ea071b0a9d9904353e]
Uploaded image to:
ghcr.io/lmussier/artifact@sha256:003f19e03f0104b91f4d247efd5578ddf59d1547ac3cb5c4695423bc0b2b4b94
lmussier@lmussier-vm:/tmp$ curl -L ghcr.io/v2/lmussier/artifact/blobs/sha256:727e12e4935c52ba62c9ffb79dc37335436eed46dc0eb6ea071b0a9d9904353e
{"errors":[{"code":"UNAUTHORIZED","message":"authentication required"}]}
```
The curl error is just here for the records, I'm not sure ghcr.io is able to provide that service, this is not the issue.
When I use oras to get the artifact back, oras is reporting an empty artifact.

```
mussier@lmussier-vm:/tmp$ oras pull --verbose ghcr.io/lmussier/artifact:cosign -o pulls
Downloading 003f19e03f01 application/vnd.oci.image.manifest.v1+json
Processing  003f19e03f01 application/vnd.oci.image.manifest.v1+json
Skipped     727e12e4935c text/plain
Skipped     b1224fda2a64 application/vnd.oci.image.config.v1+json
Downloaded  003f19e03f01 application/vnd.oci.image.manifest.v1+json
Downloaded empty artifact
Pulled [registry] ghcr.io/lmussier/artifact:cosign
Digest: sha256:003f19e03f0104b91f4d247efd5578ddf59d1547ac3cb5c4695423bc0b2b4b94
```
Is there a special thing to do / know to use artifacts?
Or oras and cosign do not share the same defintion of blob.

**Comment by znewman01** [comment]
CC @lcarva can you TAL?

**Comment by lcarva** [comment]
@lmussier , I can reproduce the reported behavior.

I'm not too familiar with using oras, but when running with the `--debug` flag, I can see that oras skips the layer containing the artifact presumably because its mediaType is `text/plain`. 

There's also the `oras blob fetch` command which I think is meant for fetching more generic OCI artifacts. Here's how I was able to get it to work:

```
🐚 cat artifact 
🐇🐇🐇🐇🐇🐇🐰
🐇🐇🐇🐇🐇🐇🐰
🐇🐇🐇🐇🐇🐇🐰

 🐚 sha256sum artifact 
297fa5e719a323da5f1fab09b2c188dc7f555d7fa0f1f48923f7c62af5e1ad0e  artifact

🐚 cosign upload blob -f artifact quay.io/lucarval/artifact:cosign
Uploading file from [artifact] to [quay.io/lucarval/artifact:cosign] with media type [text/plain]
File [artifact] is available directly at [quay.io/v2/lucarval/artifact/blobs/sha256:583f6dca722d18a73bc0e8a1802f9a12bf807ebd27379b555cd69a3a8acda1a1]
Uploaded image to:
quay.io/lucarval/artifact@sha256:7e329c577ff5ae0b123cdc3fa1ec938cfef0c581c003262970cd9ed6b5ad7378

🐚 oras blob fetch quay.io/lucarval/artifact@sha256:297fa5e719a323da5f1fab09b2c188dc7f555d7fa0f1f48923f7c62af5e1ad0e --output -
🐇🐇🐇🐇🐇🐇🐰
🐇🐇🐇🐇🐇🐇🐰
🐇🐇🐇🐇🐇🐇🐰
```

`cosign upload blob` wraps the blob in a `application/vnd.oci.image.manifest.v1+json` which appears to trip oras. oras expects the digest given to be the digest of the blob to be downloaded. It does not traverse to the layers of the manifest. For instance, here's what cosign creates:

```
🐚 skopeo inspect --raw docker://quay.io/lucarval/artifact:cosign | jq '.'
{
  "schemaVersion": 2,
  "mediaType": "application/vnd.oci.image.manifest.v1+json",
  "config": {
    "mediaType": "application/vnd.oci.image.config.v1+json",
    "size": 248,
    "digest": "sha256:a88330ba8ad0d71c0dc55ff9e1f84a44f00235f625df502535904ceae76298f8"
  },
  "layers": [
    {
      "mediaType": "text/plain",
      "size": 87,
      "digest": "sha256:297fa5e719a323da5f1fab09b2c188dc7f555d7fa0f1f48923f7c62af5e1ad0e"
    }
  ]
}
```

As you can see, the digest of the layer matches the digest of the uploaded blob.

FWIW, I think the cosign behavior here is correct. Uploading a blob without a wrapped manifest can cause the blob to be garbage collected by some registries, e.g. quay.io.

**Comment by znewman01** [comment]
Thanks @lcarva ! I think that this is working as intended, then.

@lmussier let us know if you think there's something else we should do here.

**Comment by lmussier** [comment]
Thanks  @lcarva for this very detailed answer. @znewman01 nothing more is needed, this is clear.
I've missed the fact that cosign follows "OCI blob spec" where ors push don't.

Thanks again !
