### ISSUE TITLE
Better error messages for unauthorized PATs to private packages

### ISSUE THREAD

**Issue by anderssonw** [sigstore/cosign#2930]
**Description**

*disclaimer: im not sure if this is possible / makes sense considering how PATs work*

Trying to sign an image using a PAT gave me this error:
```
Error: signing [ghcr.io/ORG/IMAGE@sha256:DIGEST]: accessing image: entity not found in registry
main.go:74: error during command execution: signing [ghcr.io/ORG/IMAGE@sha256:DIGEST]: accessing image: entity not found in registry
```

I was sort of stumped as to why it happened, but it simply turned out I had not allowed the PAT access to my organization via the SAML login.

On a public package, this error was handled quite well, telling me that the PAT was not "logged in" using SAML. However, only a 404-esque response was given for private packages.

**Comment by fool1280** [comment]
Hi, can I take this issue?

**Comment by vishal-chdhry** [comment]
Hi @fool1280, are you working on it? If you are busy then I can pick this up!

**Comment by vishal-chdhry** [comment]
Assuming that @fool1280 is inactive, I am starting to work on it.

@haydentherapper @znewman01 Is there a specific reason why we are passing a hardcoded string here? The error string should be more descriptive

https://github.com/sigstore/cosign/blob/8df14d8f5a14152cc64f0623f85378d9274753e7/pkg/oci/remote/remote.go#L52-L56
```go
ErrEntityNotFound = errors.New("entity not found in registry")
```

>  turned out I had not allowed the PAT access to my organization via the SAML login.

I think this should return a 403. But the if statement finds a 404 in the tree and returns it.

The error string in the issue is:  `accessing image: entity not found in registry`. 

Which means `ErrEntityNotFound` is returned in line 185 https://github.com/sigstore/cosign/blob/8df14d8f5a14152cc64f0623f85378d9274753e7/cmd/cosign/cli/sign/sign.go#L182-L185
_(we are only returning `accessing image:` in line 185 so that must be how)_

But we are also checking in the if statement if the error is not of type `ErrEntityNotFound` in the above if statement.

@anderssonw Are you using the latest version?

**Comment by anderssonw** [comment]
I haven't used the cosign CLI since posting this issue, so not sure what the message is now, sorry!

**Comment by znewman01** [comment]
> On a public package, this error was handled quite well, telling me that the PAT was not "logged in" using SAML. However, only a 404-esque response was given for private packages.

My hunch is that this is by design. It's pretty common for APIs to return 404s instead of 403s for private entities, in order to prevent unauthorized users for learning whether an entity exists. If that's the case, I don't know how much we can do about it client-side.

> Is there a specific reason why we are passing a hardcoded string here? The error string should be more descriptive

We'd be okay with a more descriptive error if you have a specific proposal.

**Comment by vishal-chdhry** [comment]
@znewman01 Sorry for the delay, I was busy with academic stuff. 

That exact error cannot happen anymore as [that behavior was changed in `v2.1.0`](https://github.com/sigstore/cosign/pull/2959/files#diff-72911b6572099462e5f2e8ff920f4f9228587ab100820a26d3e90377c36bd73fR182-R184). But I still believe we should change the error to be more descriptive as `ociremote.SignedEntity` is used elsewhere as well and with the current design, the error value from remote get is lost.

Sending a PR.
