### ISSUE TITLE
`cosign attest` requires `--predicate` to be passed explicitly

### ISSUE THREAD

**Issue by znewman01** [sigstore/cosign#2937]
From Slack:

@anderssonw writes:

> https://github.com/sigstore/cosign/blob/17cc13812d8a7bfbb068ffc10fdbbdb3a9416f11/cmd/cosign/cli/attest/attest.go#L135
>
> Is this working as intended? It seems an empty predicate path returns the following error:
>
> ```
> Error: signing ghcr.io/ORG/IMAGE@sha256:DIGEST: open : no such file or directory
> main.go:74: error during command execution: signing ghcr.io/ORG/IMAGE@sha256:DIGEST: open : no such file or directory
> ```
>
> This is running a keyless attest, btw:
`cosign attest --identity-token $IDENTITY_TOKEN ghcr.io/ORG/IMAGE@sha256:DIGEST`

> piping like this: `echo 'foo' | cosign attest --identity-token $IDENTITY_TOKEN ghcr.io/ORG/IMAGE@sha256:DIGEST`
does not change the error
>
> if a predicate file is required, why is it not a required flag?
>
> if i explicitly set `--predicate -` using stdin worked fine

@mattmoor:

> I was looking at this code the other day and iirc the absence of the flag causes it to use os.Stdin, so not sure why the behavior doesn’t change without a bit of digging
> 
> I wonder if there is a bad default value
>
> The default should probably be - in that case
> The flags are mostly defined in an options package, so I’d check for attest options there

**Comment by lcarva** [comment]
> The default should probably be - in that case

I believe this is the right fix.

A couple of caveats:

1. If the default value is `-`, then not providing standard input redirection causes the command to halt with this message:     `Using payload from: standard input`. We can probably detect when interactive mode is being used to provide a meaningful error message. Similar to https://github.com/sigstore/cosign/blob/83c08ce4f35116da7c74350a67d5740ca5e28ca5/cmd/cosign/cli/fulcio/fulcio.go#L148-L149
2. When using the syntax `echo 'foo' | cosign attest ...`, either `--yes` or `--no-upload` must also be provided. Otherwise, the error `user declined the prompt` is raised. This is probably ok.

**Comment by lcarva** [comment]
Alternatively, we could mark the flag as required (must not be an empty string) and let the user decide which behavior better suits their needs. This actually seems like the least surprising option.
