### ISSUE TITLE
Cosign release verification instructions succeed despite root key having expired

### ISSUE THREAD

**Issue by h4l** [sigstore/cosign#2977]
I've been going through the [Verifying Cosign Releases](https://docs.sigstore.dev/cosign/installation/#verifying-cosign-releases) section of the cosign install instructions. (I'm looking into the right way to validate an automated install of cosign.)

The instructions start with installing TUF and running :
```console
$ curl -o sigstore-root.json https://raw.githubusercontent.com/sigstore/root-signing/main/ceremony/2022-10-18/repository/5.root.json
$ tuf-client init https://tuf-repo-cdn.sigstore.dev sigstore-root.json
```

If I look at `5.root.json` (`sigstore-root.json` after downloading), I see:
```json
{
 "signed": {
     "_type": "root",
     "spec_version": "1.0",
     "version": 5,
     "expires": "2023-04-18T18:13:43Z",
     "keys": {
```

So it seems to be expired. And looking at the root-signing repo, I can see there are more recent versions which aren't expired: https://github.com/sigstore/root-signing/tree/main/repository/repository

When I proceed with the validation instructions using the expired `5.root.json` trust root, everything succeeds — the cosign binary matches the signature, and the signature matches the public key tuf-client produces.

Shouldn't this have failed though? 

From the POV of someone who isn't familiar with TUF, it's not clear to me what trust assumptions I'm making when installing go-tuf and using it to fetch the `artifact.pub` public key. My guess is that it should be checking that the key has been signed by the keys in the root, or is derived from the root in some way. But I'd expect that to fail if the root says it's expired.

I feel like the instructions could describe the security/trust model that the validation follows, as I assume most people won't be familiar with TUF.

Also, it seems like the trust hinges on trusting that downloading`https://raw.githubusercontent.com/sigstore/root-signing/main/ceremony/2022-10-18/repository/5.root.json` does is in fact result in the keys the project expects. Shouldn't there be some kind of external verification of this? Like something to tie it back to your initial signing ceremony livestream for example?

**Comment by h4l** [comment]
FWIW, I've just started using cosign to sign container images and artefacts produced in GitHub Actions CI builds, and it's been a really good experience — the docs are good and the CLI is pleasant to use, so thank you for that!

**Comment by haydentherapper** [comment]
The TUF client will download the latest root following the TUF client update workflow - https://theupdateframework.github.io/specification/latest/#detailed-client-workflow.  The TUF client will find the latest unexpired root, or fail if all roots are expired.

We start with the 5th root due to a breaking change in the root key format that was required. You can verify that the 1st root, which was signed on a livestream, chains up to the 5th root. However this requires some manual steps since the TUF client doesn't support the old format of the root, so we don't recommend it for typical workflows. https://github.com/sigstore/root-signing will have more information about this, though you might have to dig through some PRs, or feel free to file an issue there to chat more about this.

I'll file an issue in the docs repo to update with more of an explanation about verification with the TUF client.

Note that you can also verify the Cosign binary using the keyless verification (which we should document, I'll file an issue for this too), though this requires trusting the initial download of Cosign (hence why we have this manual process using TUF).

**Comment by h4l** [comment]
I see, that makes sense, thanks for explaining this. The enhancements you describe in the linked issue should cover this, so I'll close this issue.
