### ISSUE TITLE
Design: Cosign support for registries with immutable tags

### ISSUE THREAD

**Issue by dlorenc** [sigstore/cosign#313]
If a registry has "immutable tags" enabled as a feature (https://aws.amazon.com/about-aws/whats-new/2019/07/amazon-ecr-now-supports-immutable-image-tags/, for example), then cosign's model of "appending" signatures won't work for multiple signatures.

Let's figure out a workable option here. A couple options:

- Use cosign_repository to store signatures in a repo that doesn't have immutable tags enabled (this one is kind of cheating)
- If we can assume list API support (which we can't always, but maybe all the registries with immutable tags do support this), then we could use a more flexible naming convention and listing/filtering. If "sub repositories" are supported (again, they're not everywhere), we could use them to contain a group of separate signature tags that we can list.
- If we can't assume list support, we can do a numeric, predictable, sharded storage scheme. $dgst.1, $dgst.2, $dgst.3. Clients would start at 0 and keep doing HEAD requests to test for existence until something isn't found. Normally we'd have to worry about race-conditions during write, but immutable tags help us out here :)

**Comment by michaelb990** [comment]
Hey @dlorenc! I work on ECR. Let me know how we can help with this.

> Use cosign_repository to store signatures in a repo that doesn't have immutable tags enabled (this one is kind of cheating)

This one seems like the easiest option for us with the fewest "gotchas". It might be an issue for some customers if they have account or organization policies that require all repositories to have immutability enabled, but it should be workable.

> If we can assume list API support (which we can't always, but maybe all the registries with immutable tags do support this), then we could use a more flexible naming convention and listing/filtering. If "sub repositories" are supported (again, they're not everywhere), we could use them to contain a group of separate signature tags that we can list.

This could work, with some issues that could arise when a repository has a ton of tags and starts to hit issues with no paging/filtering support in the list tags API.

> If we can't assume list support, we can do a numeric, predictable, sharded storage scheme. $dgst.1, $dgst.2, $dgst.3. Clients would start at 0 and keep doing HEAD requests to test for existence until something isn't found. Normally we'd have to worry about race-conditions during write, but immutable tags help us out here :)

This would also work, I think, but might cause some issues when, for example one of the middle images gets deleted leaving a "hole" in the signature list.

Another option could be to delete the tag and recreate it, something that *is* allowed in ECR even with immutable tags enabled, though we only support deletion through the AWS API, which means it wouldn't be a portable solution.

**Comment by dlorenc** [comment]
> This one seems like the easiest option for us with the fewest "gotchas". It might be an issue for some customers if they have account or organization policies that require all repositories to have immutability enabled, but it should be workable.
> 
> >

Thanks! This was my hunch for the best path as well, and my exact concern. I think we'll push ahead with this approach unless we start hearing that it's too hard for users to disable "immutable tags" for specific repositories.

**Comment by dekkagaijin** [comment]
> Another option could be to delete the tag and recreate it, something that is allowed in ECR even with immutable tags enabled, though we only support deletion through the AWS API, which means it wouldn't be a portable solution.

Do you have a good example of prior art for that? Presumably we'd be able to use the same access token for that API request as we would for the rest of ECR? I wouldn't be _too_ opposed to special casing things a bit here if there's enough demand for sigs in repos with immutable tags

**Comment by dlorenc** [comment]
I agree, I'm fine in general with "polyfills" like this that make the tool more useful.

I think the ability to separate write permissions between the "signer" and the image repository itself is probably the most compelling reason to go with the separate repo model here though.

**Comment by michaelb990** [comment]
> prior art for that

What do you mean? [We have documentation](https://docs.aws.amazon.com/cli/latest/reference/ecr/batch-delete-image.html) for the `batch-delete-image` command, there are similar pages for each language's SDK. You'd need to use AWS credentials (not the docker auth token that is used when pushing/pulling an image), but it should work as shown below. Happy to help provide examples in golang or answer other questions.

```
❯ aws ecr batch-delete-image --repository-name <repo_name> --image-ids imageTag=<signature_tag>
{
    "imageIds": [
        {
            "imageDigest": "<signature_digest>",
            "imageTag": "<signature_tag>"
        }
    ],
    "failures": []
}
```

But I think I agree with Dan, allowing a separate repo for this would probably be the simplest solution for now.

**Comment by joaopapereira** [comment]
Hello from Carvel here,
Really appreciate the work that yll are putting into building cosign, so that we can increase our supply chain security 🥇 

> separate write permissions between the "signer" and the image repository itself is probably the most compelling reason to go with the separate repo model here though

Hmmm, what if I as a developer want to sign my own image? In this case, the developer would have to have access to write to the signatures repository.

Is there another registry that also supports immutable tags?

> Use cosign_repository to store signatures in a repo that doesn't have immutable tags enabled (this one is kind of cheating)

Feels a little bit like notary v1 need for a sidecar 😭 

Personally, I really like option 2 but only the listing part. I believe that predictability is very important so we should try to have 1 mechanism for all the registries, or else the tools would become very brittle (`if ecr then blah elseif gcr then blah`). At this point do you know which registries do not support the listing of all tags on a repository? because according to the distribution spec https://github.com/opencontainers/distribution-spec/blob/main/spec.md#content-discovery we should be able to always query for tags.

The third option really breaks as @michaelb990 was saying, if a signature is deleted we are doomed 😄

**Comment by dlorenc** [comment]
Hey @joaopapereira!

The default flow of cosign isn't changing! You can sign your own images however you want.

The suggested path here is really just for people that want to separate out permissions between the signatures repo and the images repo, or to enforce "immutable" tags. Since it's already in place via the `COSIGN_REPOSITORY` env var - I think this is really just a documentation issue to better clarify how to use cosign in this way.

I agree the need for a second repository is a bit annoying, but I'd say it's still better than notaryv1 because it's the same type of service (a repository) rather than an entirely separate database you have to run, deploy and operate :)

I *think* acr also supports immutable repositories, but I'm not sure.

Does this make sense?

**Comment by joaopapereira** [comment]
I am approaching this from a `imgpkg` perspective because if we want to allow people to copy Images or Bundles signed with cosign, `imgpkg` will have to find out where these signatures are. So having a single point of search for the signatures would be ideal.
Going to take a look at the `COSIGN_REPOSITORY` env variable that you mentioned to see how might that impact the copy of the Images.

**Comment by dlorenc** [comment]
Ah cool! Yeah that variable is used by cosign to place them in a different location.

cc @priyawadhwa @dekkagaijin - we just added a "cosign cp" command to help move things around like you're describing. Would it make sense for imgpkg to reuse that as a library?

**Comment by joaopapereira** [comment]
I will have to see it, but I think that it would make more sense for `imgpkg` to consume the finding of the image as a library since we already have a bunch of logic for copyings OCI Images

**Comment by dlorenc** [comment]
Ah cool, you can always use the "cosign.Munge" function we have to return the right location to copy.

**Comment by joaopapereira** [comment]
After some chat in https://sigstore.slack.com/archives/C01PZKDL4DP/p1621433653004700, I would like to propose this issue to use the listing tag option available in the [OCI Distribution spec](https://github.com/opencontainers/distribution-spec/blob/main/spec.md#content-discovery).

The idea here would be for `cosign` when pushing a signature to create a tag that follows the pattern `<algo>-<abc...123>.<id>.sig`.
- `<algo>` is the SHA algorithm for the image being signed (ex: `sha256`)
- `<abc...123>` is the Hex of the image being signed
- `<id>` this would be a random string of numbers and letters with a fixed size of 7. This identifier will be used to ensure there are no collisions on the signatures.

With this approach if you have a tool that is trying to fetch all the signatures for a particular image you just need to list all the available tags and try to find the ones that match your images Hex. I believe this will make the implementation easier for `cosign` since the method for searching signatures in mutable and immutable tags repository will be the same.

This approach is not 100% perfect, but I believe it could make it easier to find the signatures in a particular repository

Pros of this approach:
- Uses a standard API to find the signatures
- Can easily provide a list of all signatures without having to rewrite tags or having a secondary repository to save the signatures
- Creates consistency between immutable tags repositories and the ones that are mutable

Cons of this approach:
- Does not solve the problem of the signer requiring permission to write on the destination repository
- If a repository has thousands of tags it will be a bit of a costly operation
