### ISSUE TITLE
Cosign timestamp verification does not work with protobuf bundle format

### ISSUE THREAD

**Issue by cmurphy** [sigstore/cosign#3875]
**Description**

Signing and verifying an artifact with a legacy-format bundle with a disconnected timestamp file works:

```
$ go run cmd/cosign/main.go sign-blob /tmp/blob -y --bundle /tmp/blob.bundle --timestamp-server-url=https://freetsa.org/tsr --rekor-url http://localhost:3000 --fulcio-url http://localhost:5555 --rfc3161-timestamp=/tmp/timestamp.txtUsing payload from: /tmp/blob
Generating ephemeral keys...
Retrieving signed certificate...
[...snipped...]
Successfully verified SCT...
Timestamp fetched with time:  2024-09-10 18:58:41 +0000 UTC
RFC3161 timestamp written to file /tmp/timestamp.txt

using ephemeral certificate:
[...snipped...]
$ go run cmd/cosign/main.go verify-blob /tmp/blob --bundle /tmp/blob.bundle --rekor-url http://localhost:3000 --rfc3161-timestamp=/tmp/timestamp.txt --use-signed-timestamps --certificate-identity-regexp='.*' --certificate-oidc-issuer-regexp='.*'
Verified OK
```

Signing  an artifact with a protobuf bundle with an embedded timestamp works, but verification does not:

```
$ go run cmd/cosign/main.go sign-blob /tmp/blob -y --bundle /tmp/blob.bundle --timestamp-server-url=https://freetsa.org/tsr --rekor-url http://localhost:3000 --fulcio-url http://localhost:5555 --new-bundle-format
Using payload from: /tmp/blob
Generating ephemeral keys...
Retrieving signed certificate...
[...snipped...]
Successfully verified SCT...
Timestamp fetched with time:  2024-09-10 19:01:23 +0000 UTC
using ephemeral certificate:
[...snipped...]
$ go run cmd/cosign/main.go verify-blob /tmp/blob --bundle /tmp/blob.bundle --rekor-url http://localhost:3000 --use-signed-timestamps --certificate-identity-regexp='.*' --certificate-oidc-issuer-regexp='.*' --new-bundle-format --trusted-root /home/colleenmurphy/.sigstore/root/targets/trusted_root.json
Error: failed to verify timestamps: threshold not met for verified signed timestamps: 0 < 1
main.go:74: error during command execution: failed to verify timestamps: threshold not met for verified signed timestamps: 0 < 1
exit status 1
```

The trusted root contains the certificate chain for the given timestamp authority: https://gist.github.com/cmurphy/cf1d42615eae8bbcbe332d4b91cc4baf

If this is user error, then it should be addressed with documentation.

**Version**

```
$ git rev-parse --short HEAD
dee0b23f
```

**Comment by cmurphy** [comment]
It was indeed user error, but still something documentation could help with.

It seems like this comes down to the different TUF clients in use between cosign and sigstore-go, and the fact that the TSA I've chosen (which is recommended in the cosign help) does not have intermediate certificates, only a root and a leaf cert: https://freetsa.org/index_en.php

My TUF mirror was set up to include both a trusted_root.json and the individual TSA targets `tsa_leaf.crt.pem` and `tsa_root.crt.pem`. The Legacy TUF client used in cosign sees that there are no intermediates and so the timestamp authority verification [skips the check for the timestamping extended key usage](https://github.com/sigstore/timestamp-authority/blob/54997886b333ed5f5030063e3b6c1d809da51d42/pkg/verification/verify.go#L171-L176). When I created my trusted_root.json, I erroneously included both the leaf and the root. sigstore-go interpreted the root as an intermediate, and since it did not have the timestamping extension (which it shouldn't, as a CA), it failed to verify. Updating the trusted_root.json to only include the TSA's CA and not the leaf cert fixed the issue.

**Comment by haydentherapper** [comment]
> When I created my trusted_root.json, I erroneously included both the leaf and the root. sigstore-go interpreted the root as an intermediate, and since it did not have the timestamping extension (which it shouldn't, as a CA), it failed to verify. Updating the trusted_root.json to only include the TSA's CA and not the leaf cert fixed the issue.

Hm, you should be able to include both the CA certificate and leaf certificate for the TSA. For timestamp verification, a leaf is optional, but if present, [it will be used in verification](https://github.com/sigstore/sigstore-go/blob/fbc922a2d5060fa670b7614db183784fe3518713/pkg/verify/tsa.go#L101-L105). If the leaf is not present, then it is expected to be embedded in the signed timestamp, which is a parameter of the [timestamp request](https://www.ietf.org/rfc/rfc3161.txt#:~:text=shall%0A%20%20%20be%20rejected.-,If%20the%20certReq%20field%20is%20present,-and%20set%20to).

I think the issue is the order of the certificates in the trust root, see [the protobuf file](https://github.com/sigstore/protobuf-specs/blob/b288f87c935c02102866e2c8df2f3d66a812f446/protos/sigstore_trustroot.proto#L78-L80) which specifies the last cert in the chain should be the trust anchor, eg leaf is index 0, intermediates are 1 to n-1, and index n is the root, which is how [sigstore-go parses the cert chain](https://github.com/sigstore/sigstore-go/blob/fbc922a2d5060fa670b7614db183784fe3518713/pkg/root/trusted_root.go#L262). Looking at the gist, I think the order is flipped.
