### ISSUE TITLE
Integrate sigstore's root of trust into `cosign`

### ISSUE THREAD

**Issue by dekkagaijin** [sigstore/cosign#389]
Allows for us to validate cert chains and signatures for arbitrary images and binaries.

TODO: decide on what the UX should look like for keyless attestation of signatures

**Comment by dlorenc** [comment]
cc @asraa any thoughts here?

**Comment by asraa** [comment]
Hm! Interesting good point. Here's what you *could* do:

With the client portion of the demo code https://github.com/sigstore/cosign/pull/366:
We can fetch and validate the targets the root of trust signed (e.g. fulcio root ca and rekor public key hardcoded in cosign) before using them. Where would we want to place them the TUF metadata though?
* on a registry like the demo PR?
* we could fetch directly with HTTP on GitHub as well

In order to facilitate all of that people would need to provide / trust some initial root keys they trust (to bootstrap all of this anyway). That needs a source of truth/provision as well.

**Comment by asraa** [comment]
> We can fetch and validate the targets the root of trust signed (e.g. fulcio root ca and rekor public key hardcoded in cosign) before using them.

If it makes sense to pin the initial root in cosign and add verification for Fulcio/Rekor keys and certs, let me know! I can at least use an HTTP fetch.

**Comment by dlorenc** [comment]
Don't know how I closed this one by accident!

@dekkagaijin could you link your doc here when it's ready?
