### ISSUE TITLE
support for other private key type

### ISSUE THREAD

**Issue by shimish2** [sigstore/cosign#549]
**Question**
Does cosign supports signing images using key that does not have its type "ENCRYPTED COSIGN PRIVATE KEY".

**Comment by dlorenc** [comment]
What type of key are you trying to use?

Cosign supports several KMS systems which can work with a handful of different keys types. For local, on disk keys, we only support the PEM type you mentioned, because there is no other single widely used format that we'd recommend.

Cosign can also generate payloads that can be signed by other tools, and then upload those same signatures to a registry. This can be used to integrate with other tools and formats not natively supported in cosign.

**Comment by shimish2** [comment]
I am using normal PKI key generated using openssl.

**Comment by dlorenc** [comment]
Ah, thanks. Does it begin with BEGIN PRIVATE KEY or BEGIN ENCRYPTED PRIVATE KEY ?

I think we could add a cosign import key command to generate a cosign key from an openssl one. The encryption on the openssl keys isn't great, so I don't like the idea of encouraging the usage of them directly in cosign sign, but an import for compatibility makes sense.

**Comment by dlorenc** [comment]
Would you be interested in contributing this? I could help out and walk you through it if you're interested!

**Comment by shimish2** [comment]
It begins with BEGIN RSA PRIVATE KEY, I would be happy to contribute this.

**Comment by dlorenc** [comment]
Great! Let me know if you need any pointers to get started. I'll be available on slack tomorrow!

**Comment by dlorenc** [comment]
Import was done, so this is complete!
