### ISSUE TITLE
Consider verifying local images if they exist

### ISSUE THREAD

**Issue by priyawadhwa** [sigstore/cosign#60]
Right now `cosign verify` verifies that the remote image passed in is valid.

Maybe users would want to verify the local image they just pulled is also what they expected it to be. I'm still not sure if:
- this is a feature anyone would actually use
- if there is a way to delete the digest for an image locally but maintain the image in docker (cosign won't work without the digest)

I'll leave this issue open for a bit in case anyone has any thoughts.

**Comment by jonjohnsonjr** [comment]
I'm -1 on this. There are a half dozen different daemons and another handful of on-disk formats for what a "local image" really means.

It's convenient, but if we add first-class support for docker, we'll eventually want containerd, podman, etc etc. I'd be fine with documenting how to do it and ensuring that cosign is composable and flexible enough that it's always a one-liner, but I let's not pollute the actual code with this.

In fact... it's basically impossible with docker, because docker throws away a lot of information we need during a pull :/
