### ISSUE TITLE
`cosign verify-dockerfile` is dangerous

### ISSUE THREAD

**Issue by mattmoor** [sigstore/cosign#648]
**Description**

Today `cosign verify-dockerfile` is dangerous because it verifies and allows `FROM image:tag` vs. `FROM image@sha256:deadbeef`.  This is dangerous because even if what's currently tagged on the registry is signed properly, there is a race before the `FROM` is evaluated (what if it changes!), or (with `docker build`) it's possible that what is in the local cache(!) is what's actually used, and not what was verified! 😬 

I would propose the following two changes to eliminate this danger:
1. Change `cosign verify-dockerfile` to reject `Dockerfile`s that don't use `FROM <digest>`
2. Introduce `cosign resolve-dockerfile` that allows `FROM <tag>`, but *rewrites* the `Dockerfile` to `FROM <verified digest>`.

cc @dlorenc

**Comment by mattmoor** [comment]
cc @mlieberman85 who I was telling about this race the other day.

**Comment by dlorenc** [comment]
+1, cc @dekkagaijin I thought we already had a bug to do the in place resolution actually

**Comment by developer-guy** [comment]
we (w/@erkanzileli w/@dentrax) would love to do that issue if you let us do this @mattmoor @dlorenc

**Comment by dekkagaijin** [comment]
The behavior is consistent with plain-ol `verify`, at least.

It's becoming more and more apparent that we shouldn't have added image discovery functionality to `cosign` itself. I'm uncomfortable with the idea of adding & supporting this kind of relatively advanced functionality rather than creating built-for-purpose tooling that can be composed with `cosign` to achieve the same effect.

See also:
https://github.com/sigstore/cosign/pull/491#issuecomment-911976566
https://github.com/sigstore/cosign/pull/527#issuecomment-895418500

**Comment by dekkagaijin** [comment]
Here's a first step to begin breaking out image discovery from signature creation/verification: https://github.com/sigstore/cosign/pull/662
